name: module4_task0
on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    types: [opened, reopened]
  push:
jobs:
  deploy:
    runs-on: ubuntu-18.04
    container: golang:1.15.8-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Run setup
        working-directory: module4_task0
        run: ./setup.sh
      - name: Install markdown
        run: npm install -g markdownlint-cli
      - name: Run makefile commands
        working-directory: module4_task0
        run: |
          make help
          make unit-tests
          make integration-tests
          make post POST_NAME=kanyewestlover911 POST_TITLE="find god"
          make validate
          make build
          make package
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: task0-arti
          path: module4_task0/
      - name: Make release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            module4_task0/DEPLOY.md
            module4_task0/awesome-website.zip
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './module3_task5/dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_ID }}
        timeout-minutes: 1